name: skeleton
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.2.2
  get_it: ^7.7.0
  internet_connection_checker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
